import Head from 'next/head'
import Image from 'next/image';
import styled from 'styled-components';

const Layout = styled.div`
display: grid;
grid-template-columns: 20vw 1fr;
grid-template-areas: 
'sidebar main'
'sidebar main';
`;

const SideBar = styled.div`
width: 20vw;
background-color: ${props => props.theme.colors.blue};
grid-area: sidebar;
height: calc(100vh - 10rem);
`;

const MainView = styled.div`
grid-area: main;
text-align: left;
`;

export default function Home({ json }) {
  return (
    <div>
      <Head>
        <title>Swapi | LunarDev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <SideBar>
          <p>Sidebar</p>
        </SideBar>
        <MainView>
          <h1>Swapi</h1>
        </MainView>
      </Layout>
    </div>
  )
}